version: 0.0
os: linux
files:
  - source: /
    destination: /root/node-hello
hooks:
BeforeInstall:
  - location: scripts/BeforeInstallHook.sh
   AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
